BASE_PADDLE_DOWN_SPEED   EQU $0350
BASE_PADDLE_UP_SPEED     EQU $10000 - BASE_PADDLE_DOWN_SPEED

BASE_BALL_Y_POSITION     EQU $40
BASE_BALL_X_POSITION     EQU $50
BASE_BALL_Y_SPEED        EQU $00a0
BASE_BALL_X_SPEED        EQU $fe20
